window.SHANE = {
  dealer: {
    name: "Shane's Auto Sales",
    shortName: "Shane's",
    phone: "(818) 451-9099",
    phoneHref: "tel:+18184519099",
    email: "info@shanecars.com",
    address: "13526 Ventura Blvd",
    city: "Sherman Oaks, CA 91423",
    mapsUrl:
      "https://www.google.com/maps/search/?api=1&query=13526+Ventura+Blvd+Sherman+Oaks+CA+91423",
    mapsEmbed:
      "https://www.google.com/maps?q=13526+Ventura+Blvd,+Sherman+Oaks,+CA+91423&output=embed",
    facebook: "https://www.facebook.com/people/Shanes-Auto/61565567445845/",
    hours: [
      { days: [1, 2, 3, 4, 5], labelEn: "Mon–Fri", labelEs: "Lun–Vie", open: 10, close: 19 },
      { days: [6], labelEn: "Saturday", labelEs: "Sábado", open: 10, close: 18 },
      { days: [0], labelEn: "Sunday", labelEs: "Domingo", open: null, close: null },
    ],
  },
  vehicles: [
    {
      id: "2018-honda-cr-v-7782",
      year: 2018,
      make: "Honda",
      model: "CR-V",
      trim: "EX FWD",
      price: 18995,
      miles: 56251,
      stock: "7782",
      vin: "7FARW1H53JE027762",
      body: "SUV",
      drivetrain: "FWD",
      fuel: "Gasoline",
      transmission: "CVT",
      engine: "1.5L I4 turbo, 190 hp",
      mpg: "28/34",
      color: "White",
      featured: true,
      image: "assets/featured-crv.jpg",
      blurb:
        "Late-model compact SUV with highway miles still well under the local average. Practical for Valley commutes and weekend trips.",
    },
    {
      id: "2015-mercedes-cla-6014",
      year: 2015,
      make: "Mercedes-Benz",
      model: "CLA",
      trim: "250",
      price: 13995,
      miles: 43066,
      stock: "6014",
      vin: "WDDSJ4EB6FN245023",
      body: "Sedan",
      drivetrain: "FWD",
      fuel: "Gasoline",
      transmission: "7-speed automatic",
      engine: "2.0L I4 turbo, 208 hp",
      mpg: "26/38",
      color: "White",
      featured: true,
      image: "assets/featured-mercedes.jpg",
      blurb:
        "Low-mileage CLA with the 208-hp turbo four. Compact sedan footprint that still reads as a Mercedes on Ventura Blvd.",
    },
    {
      id: "2018-jeep-wrangler-7748",
      year: 2018,
      make: "Jeep",
      model: "Wrangler",
      trim: "Unlimited Sport S 4WD",
      price: 16995,
      miles: 120036,
      stock: "7748",
      vin: "1C4HJXDG6JW143310",
      body: "SUV",
      drivetrain: "4WD",
      fuel: "Gasoline",
      transmission: "8-speed automatic",
      engine: "3.6L V6, 285 hp",
      mpg: "18/23",
      color: "Gray",
      featured: true,
      image: "assets/featured-jeep.jpg",
      blurb:
        "Four-door Wrangler Unlimited with the 3.6L V6 and 8-speed. Open-air Valley weekends without a new-Jeep payment.",
    },
    {
      id: "2014-audi-a4-7764",
      year: 2014,
      make: "Audi",
      model: "A4",
      trim: "2.0T Premium FWD",
      price: 9995,
      miles: 53156,
      stock: "7764",
      vin: "WAUAFAFL6EA040446",
      body: "Sedan",
      drivetrain: "FWD",
      fuel: "Gasoline",
      transmission: "CVT",
      engine: "2.0L I4 turbo, 220 hp",
      mpg: "24/32",
      color: "Silver",
      image:
        "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1600&q=80",
      blurb: "Premium compact sedan with unusually low miles for the year. Turbo four, clean cabin size for city parking.",
    },
    {
      id: "2012-toyota-corolla-6007",
      year: 2012,
      make: "Toyota",
      model: "Corolla",
      trim: "LE",
      price: 8995,
      miles: 104093,
      stock: "6007",
      vin: "5YFBU4EE4CP017905",
      body: "Sedan",
      drivetrain: "FWD",
      fuel: "Gasoline",
      transmission: "4-speed automatic",
      engine: "1.8L I4, 132 hp",
      mpg: "26/34",
      color: "Silver",
      image:
        "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=1600&q=80",
      blurb: "Straightforward commuter Corolla. Known service interval, modest payment, easy parts availability.",
    },
    {
      id: "2007-jaguar-xk-7738",
      year: 2007,
      make: "Jaguar",
      model: "XK",
      trim: "Convertible RWD",
      price: 9995,
      miles: 89267,
      stock: "7738",
      vin: "SAJWA44B575B14829",
      body: "Convertible",
      drivetrain: "RWD",
      fuel: "Gasoline",
      transmission: "Automatic",
      engine: "4.2L V8, 300 hp",
      mpg: "16/25",
      color: "Silver",
      image:
        "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1600&q=80",
      blurb: "Aluminum-bodied XK convertible with the 4.2 V8. Weekend car, not a grocery-getter — priced accordingly.",
    },
    {
      id: "2005-mercedes-clk-7752",
      year: 2005,
      make: "Mercedes-Benz",
      model: "CLK",
      trim: "320 Cabriolet",
      price: 4995,
      miles: 117243,
      stock: "7752",
      vin: "WDBTK65J65F122389",
      body: "Convertible",
      drivetrain: "RWD",
      fuel: "Gasoline",
      transmission: "Automatic",
      engine: "3.2L V6, 215 hp",
      mpg: "18/25",
      color: "Black",
      image:
        "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?auto=format&fit=crop&w=1600&q=80",
      blurb: "Entry-price Mercedes cabriolet. Soft-top Valley driving without a five-figure note.",
    },
    {
      id: "2005-vw-beetle-7742",
      year: 2005,
      make: "Volkswagen",
      model: "Beetle",
      trim: "GLS Convertible",
      price: 5995,
      miles: 138192,
      stock: "7742",
      vin: "3VWCM31Y65M365064",
      body: "Convertible",
      drivetrain: "FWD",
      fuel: "Gasoline",
      transmission: "Automatic",
      engine: "2.0L I4",
      mpg: "22/30",
      color: "Yellow",
      image:
        "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=1600&q=80",
      blurb: "New Beetle convertible — light, recognizable, and under $6,000 on the lot.",
    },
    {
      id: "2018-mercedes-gla-7715",
      year: 2018,
      make: "Mercedes-Benz",
      model: "GLA",
      trim: "250 4MATIC",
      price: 7995,
      miles: 160300,
      stock: "7715",
      vin: "WDCTG4GB7JJ446225",
      body: "SUV",
      drivetrain: "AWD",
      fuel: "Gasoline",
      transmission: "7-speed dual clutch",
      engine: "2.0L I4 turbo, 208 hp",
      mpg: "24/33",
      color: "Black",
      image:
        "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1600&q=80",
      blurb: "Compact Mercedes crossover with 4MATIC. Higher miles, lower ask — a working AWD hatch in a suit.",
    },
    {
      id: "2010-honda-cr-v-7776",
      year: 2010,
      make: "Honda",
      model: "CR-V",
      trim: "EX-L AWD",
      price: 7995,
      miles: 149779,
      stock: "7776",
      vin: "5J6RE4H75AL007523",
      body: "SUV",
      drivetrain: "AWD",
      fuel: "Gasoline",
      transmission: "5-speed automatic",
      engine: "2.4L I4, 180 hp",
      mpg: "21/27",
      color: "Gray",
      image:
        "https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=1600&q=80",
      blurb: "Leather EX-L CR-V with all-wheel drive. Third-gen Honda utility that still tows a small trailer.",
    },
    {
      id: "2004-honda-civic-7770",
      year: 2004,
      make: "Honda",
      model: "Civic Hybrid",
      trim: "FWD",
      price: 4995,
      miles: 141766,
      stock: "7770",
      vin: "JHMES96674S007083",
      body: "Sedan",
      drivetrain: "FWD",
      fuel: "Hybrid",
      transmission: "Automatic",
      engine: "1.3L I4 hybrid, 93 hp",
      mpg: "47/48",
      color: "Gray",
      image:
        "https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&w=1600&q=80",
      blurb: "Early Civic Hybrid for a sub-$5k payment. High combined MPG if battery health checks out on the lot.",
    },
    {
      id: "2014-kia-soul-7701",
      year: 2014,
      make: "Kia",
      model: "Soul",
      trim: "+",
      price: 5995,
      miles: 96203,
      stock: "7701",
      vin: "KNDJP3A5XE7031795",
      body: "Hatchback",
      drivetrain: "FWD",
      fuel: "Gasoline",
      transmission: "6-speed automatic",
      engine: "2.0L I4, 164 hp",
      mpg: "23/31",
      color: "Green",
      image:
        "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=1600&q=80",
      blurb: "Boxy, easy-parking Soul with the 2.0 and under 100k miles. First-car / second-car inventory.",
    },
    {
      id: "2013-toyota-camry-7771",
      year: 2013,
      make: "Toyota",
      model: "Camry",
      trim: "SE",
      price: 6995,
      miles: 197062,
      stock: "7771",
      vin: "4T1BF1FK8DU268911",
      body: "Sedan",
      drivetrain: "FWD",
      fuel: "Gasoline",
      transmission: "6-speed automatic",
      engine: "2.5L I4, 178 hp",
      mpg: "25/35",
      color: "Black",
      image:
        "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=1600&q=70",
      blurb: "SE Camry with the 2.5. Higher miles, Toyota parts network, daily-driver price.",
    },
    {
      id: "2013-toyota-rav4-7772",
      year: 2013,
      make: "Toyota",
      model: "RAV4",
      trim: "XLE",
      price: 8995,
      miles: 194874,
      stock: "7772",
      vin: "2T3WFREV7DW063244",
      body: "SUV",
      drivetrain: "FWD",
      fuel: "Gasoline",
      transmission: "6-speed automatic",
      engine: "2.5L I4, 176 hp",
      mpg: "22/29",
      color: "Silver",
      image:
        "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1600&q=80",
      blurb: "Fourth-gen RAV4 XLE. Crossover height, Camry-related 2.5, priced for a working SUV.",
    },
    {
      id: "2012-mercedes-g550-7755",
      year: 2012,
      make: "Mercedes-Benz",
      model: "G-Class",
      trim: "G 550 4MATIC",
      price: 43995,
      miles: 94308,
      stock: "7755",
      vin: "WDCYC3HF2CX196291",
      body: "SUV",
      drivetrain: "AWD",
      fuel: "Gasoline",
      transmission: "7-speed automatic",
      engine: "5.5L V8, 382 hp",
      mpg: "12/15",
      color: "Black",
      image:
        "https://images.unsplash.com/photo-1525609004556-c46c7d6cf023?auto=format&fit=crop&w=1600&q=80",
      blurb: "Body-on-frame G 550. The lot's flagship — 5.5 V8, 4MATIC, and the square silhouette people still stop for.",
    },
    {
      id: "2016-acura-ilx-7745",
      year: 2016,
      make: "Acura",
      model: "ILX",
      trim: "Premium",
      price: 10995,
      miles: 136171,
      stock: "7745",
      vin: "19UDE2F70GA008785",
      body: "Sedan",
      drivetrain: "FWD",
      fuel: "Gasoline",
      transmission: "8-speed dual clutch",
      engine: "2.4L I4, 201 hp",
      mpg: "25/36",
      color: "Gray",
      image:
        "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1600&q=80",
      blurb: "Civic bones, Acura cabin. 201-hp 2.4 and dual-clutch — a compact sedan with a little more polish.",
    },
    {
      id: "2017-infiniti-q50-7783",
      year: 2017,
      make: "INFINITI",
      model: "Q50",
      trim: "2.0t Premium RWD",
      price: 13995,
      miles: 74750,
      stock: "7783",
      vin: "JN1CV7AP7HM641222",
      body: "Sedan",
      drivetrain: "RWD",
      fuel: "Gasoline",
      transmission: "7-speed automatic",
      engine: "2.0L I4 turbo, 208 hp",
      mpg: "23/31",
      color: "Black",
      image:
        "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1600&q=80",
      blurb: "Rear-drive Q50 with under 75k miles. Turbo four, Premium trim, sports-sedan stance without a new-car tax.",
    },
    {
      id: "2008-mercedes-s550-7724",
      year: 2008,
      make: "Mercedes-Benz",
      model: "S-Class",
      trim: "S 550",
      price: 6895,
      miles: 137083,
      stock: "7724",
      vin: "WDDNG71X28A212535",
      body: "Sedan",
      drivetrain: "RWD",
      fuel: "Gasoline",
      transmission: "7-speed automatic",
      engine: "5.5L V8, 382 hp",
      mpg: "14/21",
      color: "Gold",
      image:
        "https://images.unsplash.com/photo-1617531653332-bd46c24f2068?auto=format&fit=crop&w=1600&q=80",
      blurb: "W221 S 550 — full-size Mercedes at a compact-car price. Maintenance history matters; inspect on site.",
    },
    {
      id: "2016-honda-fit-7768",
      year: 2016,
      make: "Honda",
      model: "Fit",
      trim: "LX",
      price: 8995,
      miles: 169360,
      stock: "7768",
      vin: "JHMGK5H50GX027351",
      body: "Hatchback",
      drivetrain: "FWD",
      fuel: "Gasoline",
      transmission: "CVT",
      engine: "1.5L I4, 130 hp",
      mpg: "33/41",
      color: "Blue",
      image:
        "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=1400&q=70",
      blurb: "Magic-seat Fit LX. Small outside, tall inside, 37-mpg combined rating for city errands.",
    },
    {
      id: "2015-bmw-x4-5719",
      year: 2015,
      make: "BMW",
      model: "X4",
      trim: "xDrive28i AWD",
      price: 10895,
      miles: 119554,
      stock: "5719",
      vin: "5UXXW3C50F0M86662",
      body: "SUV",
      drivetrain: "AWD",
      fuel: "Gasoline",
      transmission: "8-speed automatic",
      engine: "2.0L I4 turbo, 240 hp",
      mpg: "20/28",
      color: "Black",
      image:
        "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1400&q=70",
      blurb: "Coupe-roof X4 xDrive. 240 hp turbo four and AWD — a driver's crossover at a used-lot number.",
    },
    {
      id: "2017-audi-a4-6015",
      year: 2017,
      make: "Audi",
      model: "A4",
      trim: "2.0T Premium FWD",
      price: 9995,
      miles: 123825,
      stock: "6015",
      vin: "WAUGNAF47HN005692",
      body: "Sedan",
      drivetrain: "FWD",
      fuel: "Gasoline",
      transmission: "7-speed automatic",
      engine: "2.0L I4 turbo, 252 hp",
      mpg: "27/37",
      color: "White",
      image:
        "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1400&q=70",
      blurb: "B9 A4 Premium with the 252-hp 2.0T. Current-generation cabin in a five-figure ask.",
    },
    {
      id: "2014-mercedes-eclass-7720",
      year: 2014,
      make: "Mercedes-Benz",
      model: "E-Class",
      trim: "E 350",
      price: 7995,
      miles: 163037,
      stock: "7720",
      vin: "WDDHF5KBXEA860065",
      body: "Sedan",
      drivetrain: "RWD",
      fuel: "Gasoline",
      transmission: "7-speed automatic",
      engine: "3.5L V6, 302 hp",
      mpg: "20/28",
      color: "Black",
      image:
        "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1400&q=70",
      blurb: "W212 E 350 sedan. Full-size Mercedes ride quality, V6, black on black.",
    },
    {
      id: "2008-mercedes-cl550-7716",
      year: 2008,
      make: "Mercedes-Benz",
      model: "CL-Class",
      trim: "CL 550",
      price: 12995,
      miles: 109526,
      stock: "7716",
      vin: "WDDEJ71X18A012080",
      body: "Coupe",
      drivetrain: "RWD",
      fuel: "Gasoline",
      transmission: "7-speed automatic",
      engine: "5.5L V8, 382 hp",
      mpg: "14/21",
      color: "Black",
      image:
        "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?auto=format&fit=crop&w=1400&q=70",
      blurb: "Pillarless CL 550 coupe. S-Class mechanicals in a two-door — inspect ABC suspension on a test drive.",
    },
    {
      id: "2020-mercedes-a220-7774",
      year: 2020,
      make: "Mercedes-Benz",
      model: "A-Class",
      trim: "A 220 Sedan FWD",
      price: 16995,
      miles: 81383,
      stock: "7774",
      vin: "W1K3G4EB7LJ223151",
      body: "Sedan",
      drivetrain: "FWD",
      fuel: "Gasoline",
      transmission: "7-speed dual clutch",
      engine: "2.0L I4 turbo, 188 hp",
      mpg: "24/35",
      color: "White",
      image:
        "https://images.unsplash.com/photo-1617531653332-bd46c24f2068?auto=format&fit=crop&w=1400&q=70",
      blurb: "Newest Mercedes on the lot. MBUX cabin, compact sedan size, 2020 model year.",
    },
    {
      id: "2016-toyota-tacoma-5218",
      year: 2016,
      make: "Toyota",
      model: "Tacoma",
      trim: "SR5",
      price: 13995,
      miles: 205391,
      stock: "5218",
      vin: "On file at the lot",
      body: "Truck",
      drivetrain: "RWD",
      fuel: "Gasoline",
      transmission: "Automatic",
      engine: "3.5L V6",
      mpg: "19/24",
      color: "Silver",
      image:
        "https://images.unsplash.com/photo-1559416523-140ddc3d238c?auto=format&fit=crop&w=1600&q=80",
      blurb: "Third-gen Tacoma SR5. Work-truck miles, Toyota midsize pickup residual.",
    },
    {
      id: "2016-bmw-428i-7749",
      year: 2016,
      make: "BMW",
      model: "4 Series",
      trim: "428i Convertible RWD",
      price: 14995,
      miles: 112560,
      stock: "7749",
      vin: "WBA3V7C5XG5A25161",
      body: "Convertible",
      drivetrain: "RWD",
      fuel: "Gasoline",
      transmission: "8-speed automatic",
      engine: "2.0L I4 turbo, 240 hp",
      mpg: "22/34",
      color: "Black",
      image:
        "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=80",
      blurb: "F33 428i convertible. Hardtop-alternative soft top, turbo four, rear-wheel drive.",
    },
    {
      id: "2013-jeep-wrangler-sahara",
      year: 2013,
      make: "Jeep",
      model: "Wrangler",
      trim: "Sahara",
      price: 14995,
      miles: 110133,
      stock: "5088",
      vin: "On file at the lot",
      body: "SUV",
      drivetrain: "4WD",
      fuel: "Gasoline",
      transmission: "Automatic",
      engine: "3.6L V6, 285 hp",
      mpg: "16/21",
      color: "Green",
      image:
        "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1600&q=80",
      blurb: "JK Sahara Wrangler. Removable top, 4WD, the trail-and-PCH combination people actually use.",
    },
    {
      id: "2016-subaru-outback-7760",
      year: 2016,
      make: "Subaru",
      model: "Outback",
      trim: "Limited",
      price: 8995,
      miles: 153458,
      stock: "7760",
      vin: "On file at the lot",
      body: "Wagon",
      drivetrain: "AWD",
      fuel: "Gasoline",
      transmission: "CVT",
      engine: "2.5L H4",
      mpg: "25/32",
      color: "Blue",
      image:
        "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1400&q=70",
      blurb: "Limited Outback with Eyesight-era cabin and standard AWD. Canyon and snow-day inventory.",
    },
    {
      id: "2017-toyota-camry-5122",
      year: 2017,
      make: "Toyota",
      model: "Camry",
      trim: "SE",
      price: 11695,
      miles: 111467,
      stock: "5122",
      vin: "On file at the lot",
      body: "Sedan",
      drivetrain: "FWD",
      fuel: "Gasoline",
      transmission: "Automatic",
      engine: "2.5L I4",
      mpg: "24/33",
      color: "Gray",
      image:
        "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=1200&q=80",
      blurb: "Last year of the XV50 Camry SE. Sport seats, 2.5 four, mid-100k miles.",
    },
    {
      id: "2014-toyota-sienna-5205",
      year: 2014,
      make: "Toyota",
      model: "Sienna",
      trim: "LE",
      price: 9995,
      miles: 168420,
      stock: "5205",
      vin: "On file at the lot",
      body: "Minivan",
      drivetrain: "FWD",
      fuel: "Gasoline",
      transmission: "Automatic",
      engine: "3.5L V6",
      mpg: "18/25",
      color: "Silver",
      image:
        "https://images.unsplash.com/photo-1527786356703-4b100091cd2c?auto=format&fit=crop&w=1600&q=80",
      blurb: "Sienna LE for school runs and IKEA. Sliding doors, V6, eight seats.",
    },
    {
      id: "2013-bmw-328i-5075",
      year: 2013,
      make: "BMW",
      model: "3 Series",
      trim: "328i xDrive",
      price: 7395,
      miles: 142880,
      stock: "5075",
      vin: "On file at the lot",
      body: "Sedan",
      drivetrain: "AWD",
      fuel: "Gasoline",
      transmission: "Automatic",
      engine: "2.0L I4 turbo, 240 hp",
      mpg: "22/33",
      color: "Black",
      image:
        "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1100&q=80",
      blurb: "F30 328i xDrive. AWD 3 Series at a Civic-adjacent price. Inspect for oil and coolant history.",
    },
  ],
};

window.SHANE.i18n = {
  en: {
    skip: "Skip to content",
    navInventory: "Inventory",
    navFinancing: "Financing",
    navAbout: "About",
    navContact: "Contact",
    navRequest: "Request a car",
    call: "Call",
    lang: "ES",
    hours: "Hours",
    openNow: "Open now",
    closedNow: "Closed",
    closedSunday: "Closed Sunday",
    directions: "Get directions",
    viewInventory: "Browse inventory",
    getPreapproved: "Get pre-approved",
    featured: "On the lot",
    seeAll: "See all vehicles",
    filters: "Filters",
    reset: "Reset",
    sort: "Sort",
    make: "Make",
    body: "Body",
    price: "Price",
    any: "Any",
    results: "vehicles",
    noResults: "No vehicles match those filters. Reset or call the lot — inventory turns over.",
    miles: "miles",
    stock: "Stock",
    vin: "VIN",
    drivetrain: "Drivetrain",
    fuel: "Fuel",
    trans: "Transmission",
    engine: "Engine",
    mpg: "EPA mpg",
    color: "Color",
    wantThis: "I want this car",
    similar: "More on the lot",
    estimator: "Payment sketch",
    down: "Down payment",
    term: "Term (months)",
    rate: "APR %",
    perMonth: "/mo est.",
    estimateNote:
      "Estimate only. Actual APR depends on credit, lender, and taxes. Not a commitment to lend.",
    apply: "Apply for this vehicle",
    callAbout: "Call about this car",
    formName: "Full name",
    formEmail: "Email",
    formPhone: "Phone",
    formMessage: "Message",
    formSubmit: "Send message",
    formSuccess: "Message recorded in this demo. Call or email the lot to reach Shane's directly.",
    required: "Required",
    footerTag: "Independent used cars on Ventura Blvd.",
    privacy: "Demo site — forms do not transmit to the live dealership.",
  },
  es: {
    skip: "Saltar al contenido",
    navInventory: "Inventario",
    navFinancing: "Financiamiento",
    navAbout: "Nosotros",
    navContact: "Contacto",
    navRequest: "Pedir un auto",
    call: "Llamar",
    lang: "EN",
    hours: "Horario",
    openNow: "Abierto ahora",
    closedNow: "Cerrado",
    closedSunday: "Cerrado domingo",
    directions: "Cómo llegar",
    viewInventory: "Ver inventario",
    getPreapproved: "Preaprobación",
    featured: "En el lote",
    seeAll: "Ver todos",
    filters: "Filtros",
    reset: "Restablecer",
    sort: "Ordenar",
    make: "Marca",
    body: "Carrocería",
    price: "Precio",
    any: "Cualquiera",
    results: "vehículos",
    noResults: "Ningún vehículo coincide. Restablece los filtros o llama al lote.",
    miles: "millas",
    stock: "Stock",
    vin: "VIN",
    drivetrain: "Tracción",
    fuel: "Combustible",
    trans: "Transmisión",
    engine: "Motor",
    mpg: "mpg EPA",
    color: "Color",
    wantThis: "Quiero este auto",
    similar: "Más en el lote",
    estimator: "Estimación de pago",
    down: "Enganche",
    term: "Plazo (meses)",
    rate: "APR %",
    perMonth: "/mes est.",
    estimateNote:
      "Solo es una estimación. El APR real depende del crédito, el prestamista y los impuestos.",
    apply: "Solicitar este vehículo",
    callAbout: "Llamar por este auto",
    formName: "Nombre completo",
    formEmail: "Correo",
    formPhone: "Teléfono",
    formMessage: "Mensaje",
    formSubmit: "Enviar",
    formSuccess: "Mensaje registrado en esta demo. Llama o escribe al lote para contactar a Shane's.",
    required: "Obligatorio",
    footerTag: "Autos usados independientes en Ventura Blvd.",
    privacy: "Sitio de demostración: los formularios no se envían al concesionario en vivo.",
  },
};
